language: java

install:
#- git clone https://github.com/apache/incubator-s4.git
#- cd incubator-s4
#- gradle wrapper
#- gradle install
#- gradle s4-tools::installApp
#- cd ..
- echo "<settings><servers><server><id>sonatype-nexus-snapshots</id><username>${SOSS_USERNAME}</username><password>${SOSS_PASSWORD}</password></server></servers></settings>" > ${HOME}/.m2/settings.xml
- cat ${HOME}/.m2/settings.xml

script: if [[ $TRAVIS_SECURE_ENV_VARS -eq "true" ]]; then CMD=deploy; else CMD=install; fi; mvn -B -Plocal,storm $CMD

notifications:
  email: 
  on_success: never
  on_failure: change

env:
  global:
  - secure: ddoXIm1mkFYsExXvgPC+Q96Bpj8Kj2SWQV9GFPu09f4DaOftzag9G9mNKgvKuL9yysFklR5r33ibvs5hbz8of1NiAhkGTSxYaEqsaVdoMKBy8lU14yK6MwcH+VztmPS0Y01EOIDQWOpTuNcxbRkcLc7I8Rt0ltssXfKy6IsEQ8Y=
  - secure: E3qEgh8UlInabIMCZa/5IjB5rb1XtR/8uCUwS+hoyRmiyhXWm5x129auEouDNPBqJlz+ZXz2qNEg+3cgv6FOnQMGUy17W+VyCVKg+E15JRBYfomhpK0Sibm6kBAvMbZiE1LApTgpbzNDEdYjGE6ySVRqm2G31Zy6R5Zgg1fHnpg=
